---
title: "fish-in-space"
author: "Leonardo Feitosa"
date: "04/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rnaturalearth)
library(sf)
library(here)
library(tmap)
library(janitor)
library(tmaptools)
```

```{r}
# Set directories
basedir <- "G:/Meu Drive/fish_mgmt_areas/data"
indir <- file.path(basedir, "uruguay", "raw")
outdir <- file.path(basedir, "uruguay", "processed")
plotdir <- "figures"
```


```{r}
# read in the data
df_orig_raw <- st_read(file.path(indir, "c302Polygon.shp")) %>% 
  clean_names()

uru_rds <- readRDS(file.path(outdir, "Uruguay_anchovy.Rds")) %>% 
  clean_names()

# rnaturalearth data
world <- ne_countries(scale = "medium", returnclass = "sf")
```

```{r}
uru_rds <- uru_rds %>% 
  mutate(citation = "Direcci贸n Nacional de Calidad y Evaluaci贸n Ambiental. (07 June 2017). Anchovy fisheries prohibited area. https://www.ambiente.gub.uy/geoservicios/. Retrieved 28 July 2022: https://www.ambiente.gub.uy/geoserver/u19600217/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=u19600217:c302&outputFormat=SHAPE-ZIP")
```


```{r}
# Set coordinate system
wgs84 <- st_crs("+proj=longlat +datum=WGS84")
```

```{r}
# Inspect attribute table
df <- df_orig_raw %>% 
  st_drop_geometry() 
```

```{r}
df_final <- df_orig_raw %>%   
  mutate(dataset = "Stripped weakfish fisheries prohibited area",
         dataset_esp = "Veda pesca pescadilla",
        country = "Uruguay",
        ocean = "Atlantic",
        region = "East coast",
        agency = "Ministry of Environment of Uruguay",
        zone_id = as.character(id),
        zone_name = area_veda,
        type = "exclusion zone",
        species = "stripped weakfish",
        species_list = NA,
        source = "https://www.ambiente.gub.uy/geoserver/u19600217/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=u19600217:c302&outputFormat=SHAPE-ZIP",
        citation = "Direcci贸n Nacional de Calidad y Evaluaci贸n Ambiental. (07 June 2017). Stripped weakfish fisheries prohibited area. https://www.ambiente.gub.uy/geoservicios/. Retrieved 28 July 2022: https://www.ambiente.gub.uy/geoserver/u19600217/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=u19600217:c302&outputFormat=SHAPE-ZIP",
        created = "2017-06-07") %>% 
  select(dataset,dataset_esp, country, ocean, region, agency, zone_id, zone_name, type, species, species_list, source, citation, created) %>% 
 st_transform(wgs84)
```

```{r}
# Create output RDS file
saveRDS(uru_rds, file = file.path(outdir, "Uruguay_anchovy.Rds"))
```

```{r}
ggplot() +
#  geom_sf(data = world) +
  geom_sf(data = chile_shp, fill= NA) 
  coord_sf(xlim = c(-160, -155),
           ylim = c(18, 24)) 
```

```{r}
stur_1 <- st_read(file.path(indir, "SturgeonAtlantic_AtlanticSubspecies_SouthAtlanticDPS_20170817.shp")) %>% 
  clean_names()   

stur_2 <- st_read(file.path(indir, "SturgeonAtlantic_AtlanticSubspecies_NewYorkBightDPS_20170817.shp")) %>% 
  clean_names()  

stur_3 <- st_read(file.path(indir, "SturgeonAtlantic_AtlanticSubspecies_GulfofMaineDPS_20170817.shp")) %>% 
  clean_names()  

stur_4 <- st_read(file.path(indir, "SturgeonAtlantic_AtlanticSubspecies_CarolinaDPS_20170817.shp")) %>% 
  clean_names()  

wash_10 <- st_read(file.path(indir, "washington_state_fish_mgmt_areas10.shp")) %>% 
  clean_names()  

wash_12 <- st_read(file.path(indir, "washington_state_fish_mgmt_areas12.shp")) %>% 
  clean_names() 

wash_14 <- st_read(file.path(indir, "washington_state_fish_mgmt_areas14.shp")) %>% 
  clean_names()  

stur_all <- bind_rows(stur_1, stur_2, stur_3, stur_4) %>% 
   st_transform(wgs84)

stur_all_drop <- stur_all %>% 
  st_drop_geometry()
```


```{r}
costa_rica_atl <- readRDS(file.path(outdir, "Costa_Rica_Marine_Areas_of_Responsible_Fishing_Pacific.Rds"))

argentina <- st_zm(argentina, drop = TRUE, what = "ZM")

st_write(argentina, file.path(outdir, "Argentina_fisheries_management_areas.shp"))
```

