---
title: "merging_code"
author: "Leonardo Feitosa"
date: "27/07/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(sf)
library(reshape2)
library(rnaturalearth)
```

```{r}
# Create file paths
# Set directories
basedir <- "G:/Meu Drive/fish_mgmt_areas/data"
indir <- file.path(basedir, "us_east_coast", "raw")
outdir <- file.path(basedir, "us_east_coast", "processed")
out_final <- file.path(basedir, "processed_files")
plotdir <- "figures"
```

```{r}

world <- ne_countries(scale = "medium", returnclass = "sf")
# read in the data
df_orig <- st_read(file.path(out_final, "USA_sturgeon.shp")) 

stur_2 <- st_read(file.path(out_final, "USA_sturgeon2.shp"))

east_coast <- list.files(file.path(outdir),
                    pattern = "*.Rds",
                    full.names = TRUE)

east_coast_tbl <- sapply(east_coast, readRDS, simplify = FALSE) 

east_coast_tbl_2 <- east_coast_tbl %>% 
  bind_rows() 

sturgeon <- east_coast_tbl %>% 
  bind_rows() %>% 
  filter(species == "atlantic sturgeon")

right_whale <- east_coast_tbl %>% 
  bind_rows() %>% 
  filter(species == "right whale")
```

```{r}
# wrangling and plotting
df_orig_geo <- df_orig %>% 
  st_drop_geometry()

stur_2_geo <- df_sturg %>% 
  st_drop_geometry()

east_coast_tbl_geo <- east_coast_tbl_2 %>%
  st_drop_geometry()

whale_geo <- df_whale %>% 
  st_drop_geometry()

df_orig_geo <- df_orig %>% 
  st_drop_geometry()

df_final_geo <- df_final %>% 
  st_drop_geometry()
```

```{r}
df_whale <- right_whale %>%  
  mutate(pk_sy_h = NA,
         fk_sy = NA,
         nm_eng = dataset,
         nm_loc = dataset,
         add_des = zone_name,
         code = NA,
         mltsps = NA,
         mltspsc = species,
         fk_sy_t = NA,
         fk_sy_c = type,
         fk_sy_o = "NOAA",
         fk_sy_s = NA,
         sourc = source,
         sourc_d = "2022-07-28",
         usage = NA,
         lineage = "Downloaded and imported from NOAA on 2022-07-28",
         comment = NA,
         crtd_by = "Leonardo Manir Feitosa",
         crtd_on = "2022-07-28",
         chngd_by = NA,
         chngd_on = NA) %>% 
  relocate(source, .before = sourc_d) %>% 
  mutate(source = case_when(
    dataset == "North Atlantic Right Whale Seasonal Management Areas (SMA)" ~ "NOAA Fisheries. (18 October 2019). North Atlantic Right Whale Seasonal Management Areas (SMA). https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/north-atlantic-right-whale-seasonal-management-areas-sma-map-gis-data"
  )) %>% 
    select(-dataset, -country, -ocean, -region, -agency, -zone_id, -zone_name, -species, -sourc, -type, -species_list, -Id, -AREA_NAME)  
```


```{r}
df_sturg <- sturgeon %>%  
  mutate(pk_sy_h = NA,
         fk_sy = NA,
         nm_eng = dataset,
         nm_loc = dataset,
         add_des = zone_name,
         code = NA,
         mltsps = NA,
         mltspsc = species,
         fk_sy_t = NA,
         fk_sy_c = type,
         fk_sy_o = "NOAA",
         fk_sy_s = NA,
         sourc = source,
         sourc_d = "2022-07-28",
         usage = NA,
         lineage = "Downloaded and imported from NOAA on 2022-07-28",
         comment = NA,
         crtd_by = "Leonardo Manir Feitosa",
         crtd_on = "2022-07-28",
         chngd_by = NA,
         chngd_on = NA) %>% 
  relocate(source, .before = sourc_d) %>% 
  mutate(source = case_when(
    dataset == "Atlantic Sturgeon critical Habitat" ~ "NOAA Fisheries. (18 April 2022). Atlantic Sturgeon Critical Habitat. https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/atlantic-sturgeon-critical-habitat-map-and-gis-data"
  )) %>% 
    select(-dataset, -country, -ocean, -region, -agency, -zone_id, -zone_name, -species, -sourc, -type, -species_list, -Id, -AREA_NAME)  
```


```{r}
df_final <- east_coast_tbl_2 %>%  
  mutate(pk_sy_h = NA,
         fk_sy = NA,
         nm_eng = dataset,
         nm_loc = dataset,
         add_des = zone_name,
         code = NA,
         mltsps = NA,
         mltspsc = species,
         fk_sy_t = NA,
         fk_sy_c = type,
         fk_sy_o = "NOAA",
         fk_sy_s = NA,
         sourc = source,
         sourc_d = "2022-07-28",
         usage = NA,
         lineage = "Downloaded and imported from NOAA on 2022-07-28",
         comment = NA,
         crtd_by = "Leonardo Manir Feitosa",
         crtd_on = "2022-07-28",
         chngd_by = NA,
         chngd_on = NA) %>% 
  relocate(source, .before = sourc_d) %>% 
  mutate(mltsps = case_when(
    str_detect(mltspsc, "multi") ~ "1",
    TRUE ~ "0"
  )) %>% 
  mutate(mltspsc = case_when(
    str_detect(mltspsc, "multi") ~ species_list,
    str_detect(dataset, "Octo") ~ "octocorals",
    dataset == "Shrimp Fishery Access Areas" ~ "shrimp",
    TRUE ~ mltspsc
  )) %>% 
  mutate(nm_eng = case_when(
    str_detect(dataset, "HAPC") ~ "Oculina Bank HAPC",
    TRUE ~ nm_eng
  )) %>% 
  mutate(nm_loc = case_when(
    str_detect(dataset, "HAPC") ~ "Oculina Bank HAPC",
    TRUE ~ nm_loc
  )) %>% 
  mutate(source = case_when(
    str_detect(dataset, "South Carolina") ~ "State of South Carolina Health and Environment Control. (10 March 2021). Shellfish Management Areas. https://sc-department-of-health-and-environmental-control-gis-sc-dhec.hub.arcgis.com/. Retrieved 28 July 2022: https://sc-department-of-health-and-environmental-control-gis-sc-dhec.hub.arcgis.com/datasets/SC-DHEC::shellfish-management-areas/explore?location=32.973471%2C-79.754500%2C8.99",
    str_detect(dataset, "Defined") ~ "NOAA Fisheries. (01 July 2013). South Atlantic Off States EEZ. https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/defined-fishery-management-areas-south-atlantic-states-map-gis-data",
    str_detect(dataset, "Commercial Vessel") ~ "NOAA Fisheries. (01 July 2013). https://www.fisheries.noaa.gov/. Commercial Vessel Permits for South Atlantic Snapper-Grouper Fishery Management. Retrieved 28 july 2022: https://www.fisheries.noaa.gov/resource/map/commercial-vessel-permits-south-atlantic-snapper-grouper-fishery-management-map-gis",
    dataset == "Sea Bass Pot and Associated Buoy Gear Identification" ~ "NOAA Fisheries. (01 July 2013). Sea Bass Pot and Associated Buoy Gear Identification. https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/sea-bass-pot-and-associated-buoy-gear-identification-fishery-management-area-map-gis",
    dataset == "Longline Prohibited Areas" ~ "NOAA Fisheries. (01 July 2013). Longline Prohibited Areas Fishery Management Areas. https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/longline-prohibited-areas-fishery-management-areas-map-gis-data",
    dataset == "Special Management Zones (SMZs)" ~ "NOAA Fisheries. (01 July 2013). Special Management Zones (SMZs). https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/special-management-zones-smzs-fishery-management-areas-map-gis-data",
    dataset == "Sea Bass Pot Prohibited Area" ~ "NOAA Fisheries. (01 July 2013). Sea Bass Pot Prohibited Area Fishery Management Area. https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/sea-bass-pot-prohibited-area-fishery-management-area-map-gis-data",
    dataset == "Marine Protected Areas (MPAs) Fishery Management Areas" ~ "NOAA Fisheries. (01 July 2013). Marine Protected Areas (MPAs) Fishery Management Areas. https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/marine-protected-areas-mpas-fishery-management-areas-map-gis-data",
    dataset == "Spawning Species Management Zones (SMZs)" ~ "NOAA Fisheries. (01 July 2013). Spawning Special Management Zones (SMZs). https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/marine-protected-areas-mpas-fishery-management-areas-map-gis-data",
    dataset == "Allowable Octocoral Closed Areas" ~ "NOAA Fisheries. (01 July 2013). Allowable Octocoral Closed Areas. https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/allowable-octocoral-closed-area-fishery-management-area-map-gis-data",
    str_detect(dataset, "Experimental") ~ "NOAA Fisheries. (01 July 2013). Oculina Bank Experimental Closed Area. https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/oculina-bank-hapc-and-experimental-closed-area-fishery-management-area-map-gis-data",
    dataset == "Oculina Bank HAPC" ~ "NOAA Fisheries. (01 July 2013). Oculina Bank HAPC. https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/oculina-bank-hapc-and-experimental-closed-area-fishery-management-area-map-gis-data",
    dataset == "Shrimp Fishery Access Areas" ~ "NOAA Fisheries. (01 July 2013). Shrimp Fishery Access Areas. https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/shrimp-fishery-access-areas-fishery-management-areas-map-gis-data",
    dataset == "Golden Crab Fishery Access Areas" ~ "NOAA Fisheries. (01 July 2013). Golden Crab Fishery Access Areas. https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/golden-crab-fishery-access-areas-fishery-management-areas-map-gis-data",
    str_detect(dataset, "Charleston") ~ "NOAA Fisheries. (01 July 2013). Charleston Bump Closed Area. https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/charleston-bump-closed-area-fishery-management-area-map-gis-data",
    dataset == "Northeastern United States Closed Area" ~ "NOAA Fisheries. (01 July 2013). Northeastern United States Closed Area. https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/northeastern-united-states-closed-area-fishery-management-area-map-gis-data",
    dataset == "Smalltooth Sawfish Critical Habitat" ~ "NOAA Fisheries. (01 July 2013). Smalltooth Sawfish Critical Habitat. https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/smalltooth-sawfish-critical-habitat-map-and-gis-data",
    dataset == "East Florida Coast Longline Closed Area" ~ "NOAA Fisheries. (01 July 2013). East Florida Coast Longline Closed Area. https://www.fisheries.noaa.gov/. Retrieved 28 July 2022: https://www.fisheries.noaa.gov/resource/map/east-florida-coast-closed-area-fishery-management-area-map-gis-data",
    dataset == "MaineDMR Lobster Management - Lobster Conservation Areas" ~ "Maine DMR Open Data. (5 April 2022). MaineDMR Lobster Management - Lobster Conservation Areas. https://dmr-maine.opendata.arcgis.com/. Retrieved 28 July 2022: https://dmr-maine.opendata.arcgis.com/datasets/maine::mainedmr-lobster-management-lobster-conservation-areas/about",
    dataset == "MaineDMR Lobster Boundaries - Lobster Zones" ~ "Maine DMR Open Data. (24 September 2021). MaineDMR Lobster Boundaries - Lobster Zones. https://dmr-maine.opendata.arcgis.com/. Retrieved 28 July 2022: https://dmr-maine.opendata.arcgis.com/datasets/maine::mainedmr-lobster-boundaries-lobster-zones/about",
    dataset == "MaineDMR Scallop Management - Scallop Zones" ~ "Maine DMR Open Data. (20 March 2019). MaineDMR Lobster Boundaries - Lobster Zones. https://dmr-maine.opendata.arcgis.com/. Retrieved 28 July 2022: https://dmr-maine.opendata.arcgis.com/datasets/maine::mainedmr-scallop-management-scallop-zones/explore?location=43.954756%2C-68.814750%2C8.00"
  )) %>% 
  select(-dataset, -country, -ocean, -region, -agency, -zone_id, -zone_name, -species, -sourc, -type, -AREA_NAME, -species_list)  


df_final2 <- st_collection_extract(df_final, "POLYGON")
```

```{r}
# export shapefile
st_write(df_whale, file.path(out_final, "USA_right_whale2.shp"))
```
 
```{r}
ggplot() +
  geom_sf(data = world) +
  geom_sf(data = df_orig, aes(fill = nm_ngls),
          show.legend = F) +
  coord_sf(xlim = c(-90, -50),
           ylim = c(20, 50))
```

