---
title: "fish-in-space"
author: "Leonardo Feitosa"
date: "04/04/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rnaturalearth)
library(sf)
library(janitor)
```

```{r}
# Set directories
basedir <- "G:/Meu Drive/fish_mgmt_areas/data"
indir <- file.path(basedir, "brazil", "raw")
outdir <- file.path(basedir, "brazil", "processed")
plotdir <- "figures"
```


```{r}
# read in the data
df_orig_raw <- st_read(file.path(indir, "ZonaCosteiraMarinha_FINAL.shp")) %>% 
  clean_names()

# rnaturalearth data
world <- ne_countries(scale = "medium", returnclass = "sf")
```

```{r}
# Set coordinate system
wgs84 <- st_crs("+proj=longlat +datum=WGS84")
```

```{r}
# Inspect attribute table
df <- df_orig_raw %>% 
  st_drop_geometry() 

df2 <- c_rica %>% 
  st_drop_geometry() 
```

```{r}
# data wrangling for formating according to internal format
df_final <- df_orig_raw %>%   
  mutate(dataset = "Brazilian coast elasmobranch management zones",
         dataset_prt = "Zonas de manejo para elasmobrânquios costa brasileira",
        country = "Brazil",
        ocean = "Atlantic",
        region = "East South America",
        agency = "ICMBIO",
        zone_id = as.character(objectid),
        zone_name = nome_ap,
        type = "critical habitat",
        species = "multi-species",
        species_list = NA,
        source = "Received by email from Rodrigo Barreto (rodrigorpbarreto@gmail.com) on 2022/04/18",
        citation = "ICMBIO. (). Brazilian coast elasmobranch management zones. https://www.icmbio.gov.br/. Received by email from Rodrigo Barreto (rodrigorpbarreto@gmail.com) on 2022/04/18",
  created = NA) %>% 
  select(dataset, dataset_prt, country, ocean, region, agency, zone_id, zone_name, type, species, species_list, source, citation, created) %>% 
 st_transform(wgs84)
```

```{r}
# Create output RDS file
saveRDS(df_final, file = file.path(outdir, "Brazil_all.Rds"))
```

```{r}
# code for checking plots
ggplot() +
#  geom_sf(data = world) +
  geom_sf(data = df_orig_raw, fill= NA) 
  coord_sf(xlim = c(-160, -155),
           ylim = c(18, 24)) 
```
